library(mediation)
Memory <- read.table("Chap7_Memory.txt")
colnames(Memory) = c("id", "x", "m", "r", "y")
model.mMemory <- lm(m~x, data=Memory)
model.yMemory <- lm(y~x+m+x:m, data=Memory)
out.Memory <- mediate(model.mMemory, model.yMemory, sims=1000, treat="x", mediator="m", boot = TRUE)
summary(model.mMemory)
summary(model.yMemory)
summary(out.Memory)
out.Memory.QuasiBayes <- mediate(model.mMemory, model.yMemory, sims=1000, treat="x", mediator="m", boot = FALSE)
summary(out.Memory.QuasiBayes)
